[package]
name = "grabapl"
version = "0.1.0"
edition = "2024"

[lib]
name = "grabapl"

[dependencies]
petgraph = { git = "https://github.com/petgraph/petgraph.git", rev = "e2b28e59d0c37a8db9037997e84cc483ca94afc9"}