// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type MyFFIStruct_obj = {
    a: number;
    b: boolean;
};



export class MyFFIStruct {
    get a(): number;
    set a(value: number);
    get b(): boolean;
    set b(value: boolean);
    /** Create `MyFFIStruct` from an object that contains all of `MyFFIStruct`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    static fromFields(structObj : MyFFIStruct_obj) : MyFFIStruct;



    static create(): MyFFIStruct;

    doAThing(): void;

    constructor(structObj: MyFFIStruct_obj);
}