[workspace]
resolver = "2"
members = ["grabapl", "example_clients/simple_semantics/simple_semantics", "example_clients/simple_semantics/simple_semantics_ffi", "playground/derive_more_debug_test"]
exclude = ["playground", "wasm-game-of-life"]
