[workspace]
resolver = "2"
members = ["grabapl", "example_clients/simple_semantics/simple_semantics", "example_clients/simple_semantics/simple_semantics_ffi", "repl"]
exclude = ["playground", "wasm-game-of-life"]

[profile.release]
# TODO: remove again?
debug = true