/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const Context_init: () => void;
export const Context_parse: (a: number, b: number) => number;
export const OpCtxAndFnNames_destroy: (a: number) => void;
export const ParseError_to_string: (a: number, b: number) => void;
export const ParseError_destroy: (a: number) => void;
export const ParseResult_error_message: (a: number, b: number) => void;
export const ParseResult_dot_of_state: (a: number, b: number, c: number, d: number) => void;
export const ParseResult_list_states: (a: number) => number;
export const ParseResult_destroy: (a: number) => void;
export const StringIter_next: (a: number) => number;
export const StringIter_to_iterable: (a: number) => number;
export const StringIter_destroy: (a: number) => void;
export const StringWrapper_new: (a: number, b: number) => number;
export const StringWrapper_to_string: (a: number, b: number) => void;
export const StringWrapper_destroy: (a: number) => void;
export const diplomat_init: () => void;
export const diplomat_simple_write: (a: number, b: number, c: number) => void;
export const diplomat_buffer_write_create: (a: number) => number;
export const diplomat_buffer_write_get_bytes: (a: number) => number;
export const diplomat_buffer_write_len: (a: number) => number;
export const diplomat_buffer_write_destroy: (a: number) => void;
export const diplomat_alloc: (a: number, b: number) => number;
export const diplomat_free: (a: number, b: number, c: number) => void;
export const diplomat_is_str: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_start: () => void;
