/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const CompileResult_dot_of_state: (a: number, b: number, c: number, d: number) => void;
export const CompileResult_get_program: (a: number, b: number) => void;
export const CompileResult_destroy: (a: number) => void;
export const ConcreteGraph_create: () => number;
export const ConcreteGraph_dot: (a: number, b: number) => void;
export const ConcreteGraph_add_node: (a: number, b: number, c: number, d: number) => void;
export const ConcreteGraph_add_edge: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const ConcreteGraph_destroy: (a: number) => void;
export const Grabapl_init: () => void;
export const Grabapl_parse: (a: number, b: number) => number;
export const Grabapl_destroy: (a: number) => void;
export const OperationBuilder_create: (a: number, b: number) => number;
export const OperationBuilder_expect_parameter_node: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const OperationBuilder_destroy: (a: number) => void;
export const OperationContext_create: () => number;
export const OperationContext_destroy: (a: number) => void;
export const Program_op_ctx: (a: number) => number;
export const Program_run_operation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const Program_destroy: (a: number) => void;
export const StringError_to_string: (a: number, b: number) => void;
export const StringError_destroy: (a: number) => void;
export const diplomat_init: () => void;
export const diplomat_simple_write: (a: number, b: number, c: number) => void;
export const diplomat_buffer_write_create: (a: number) => number;
export const diplomat_buffer_write_get_bytes: (a: number) => number;
export const diplomat_buffer_write_len: (a: number) => number;
export const diplomat_buffer_write_destroy: (a: number) => void;
export const diplomat_alloc: (a: number, b: number) => number;
export const diplomat_free: (a: number, b: number, c: number) => void;
export const diplomat_is_str: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_start: () => void;
