// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class AbstractNodeId {
    get ffiValue(): pointer;


    static newParameter(marker: number): AbstractNodeId;

    static newFromOutput(opMarker: string, nodeMarker: string): AbstractNodeId;

    static newFromStr(aid: string): AbstractNodeId;
}