// generated by diplomat-tool
import { AbstractNodeId } from "./AbstractNodeId.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const AbstractArgList_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.AbstractArgList_destroy(ptr);
});

export class AbstractArgList {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("AbstractArgList is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            AbstractArgList_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.AbstractArgList_create();

        try {
            return new AbstractArgList(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    push(arg) {
    wasm.AbstractArgList_push(this.ffiValue, arg.ffiValue);

        try {}

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}