// generated by diplomat-tool
import type { AbstractNodeId } from "./AbstractNodeId"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class AbstractArgList {
    get ffiValue(): pointer;


    static create(): AbstractArgList;

    push(arg: AbstractNodeId): void;
}