// generated by diplomat-tool
import type { AbstractNodeId } from "./AbstractNodeId"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class AbstractArgList {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): AbstractArgList;

    push(arg: AbstractNodeId): void;
}