// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class BuilderOpLike {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static newFromId(opId: number): BuilderOpLike;

    static newRecurse(): BuilderOpLike;

    static newAddNode(): BuilderOpLike;

    static newAddEdge(): BuilderOpLike;

    static newSetEdgeValue(value: string): BuilderOpLike;
}