// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class BuiltinQuery {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static newIsValueGt(value: number): BuiltinQuery;

    static newIsValueEq(value: number): BuiltinQuery;

    static newValuesEqual(): BuiltinQuery;

    static newFirstGtSnd(): BuiltinQuery;
}