// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class BuilderOpLike {
    get ffiValue(): pointer;


    static newFromId(opId: number): BuilderOpLike;

    static newRecurse(): BuilderOpLike;
}