// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const BuilderOpLike_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.BuilderOpLike_destroy(ptr);
});

export class BuilderOpLike {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("BuilderOpLike is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            BuilderOpLike_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    get ffiValue() {
        return this.#ptr;
    }


    static newFromId(opId) {

        const result = wasm.BuilderOpLike_new_from_id(opId);

        try {
            return new BuilderOpLike(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newRecurse() {

        const result = wasm.BuilderOpLike_new_recurse();

        try {
            return new BuilderOpLike(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newAddNode() {

        const result = wasm.BuilderOpLike_new_add_node();

        try {
            return new BuilderOpLike(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newAddEdge() {

        const result = wasm.BuilderOpLike_new_add_edge();

        try {
            return new BuilderOpLike(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newSetEdgeValue(value) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const valueSlice = diplomatRuntime.DiplomatBuf.str8(wasm, value);

        const result = wasm.BuilderOpLike_new_set_edge_value(...valueSlice.splat());

        try {
            return new BuilderOpLike(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            functionCleanupArena.free();

        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}