// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class BuiltinQuery {
    get ffiValue(): pointer;


    static newIsValueGt(value: number): BuiltinQuery;

    static newIsValueEq(value: number): BuiltinQuery;

    static newValuesEqual(): BuiltinQuery;

    static newFirstGtSnd(): BuiltinQuery;
}