// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const BuiltinQuery_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.BuiltinQuery_destroy(ptr);
});

export class BuiltinQuery {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("BuiltinQuery is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            BuiltinQuery_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static newIsValueGt(value) {

        const result = wasm.BuiltinQuery_new_is_value_gt(value);

        try {
            return new BuiltinQuery(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newIsValueEq(value) {

        const result = wasm.BuiltinQuery_new_is_value_eq(value);

        try {
            return new BuiltinQuery(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newValuesEqual() {

        const result = wasm.BuiltinQuery_new_values_equal();

        try {
            return new BuiltinQuery(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newFirstGtSnd() {

        const result = wasm.BuiltinQuery_new_first_gt_snd();

        try {
            return new BuiltinQuery(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}