// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ConcreteGraph {
    get ffiValue(): pointer;


    static create(): ConcreteGraph;

    addNode(value: number): void;

    sayHi(): void;
}