// generated by diplomat-tool
import { ConcreteGraph } from "./ConcreteGraph.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const DotCollector_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.DotCollector_destroy(ptr);
});

export class DotCollector {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("DotCollector is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            DotCollector_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.DotCollector_create();

        try {
            return new DotCollector(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    collect(graph) {
    wasm.DotCollector_collect(this.ffiValue, graph.ffiValue);

        try {}

        finally {
        }
    }

    getDot() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.DotCollector_get_dot(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}