// generated by diplomat-tool
import type { ConcreteGraph } from "./ConcreteGraph"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class DotCollector {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): DotCollector;

    collect(graph: ConcreteGraph): void;

    getDot(): string;
}