// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class EdgeAbstract {
    get ffiValue(): pointer;


    static newWildcard(): EdgeAbstract;

    static newExact(exact: string): EdgeAbstract;
}