// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const EdgeAbstract_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.EdgeAbstract_destroy(ptr);
});

export class EdgeAbstract {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("EdgeAbstract is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            EdgeAbstract_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    get ffiValue() {
        return this.#ptr;
    }


    static newWildcard() {

        const result = wasm.EdgeAbstract_new_wildcard();

        try {
            return new EdgeAbstract(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    static newExact(exact) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const exactSlice = diplomatRuntime.DiplomatBuf.str8(wasm, exact);

        const result = wasm.EdgeAbstract_new_exact(...exactSlice.splat());

        try {
            return new EdgeAbstract(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            functionCleanupArena.free();

        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}