// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class EdgeAbstract {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static newWildcard(): EdgeAbstract;

    static newExact(exact: string): EdgeAbstract;
}