// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class IntermediateState {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    getDot(): string;

    availableAids(): string;

    queryContext(): string;
}