// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class IntermediateState {
    get ffiValue(): pointer;


    getDot(): string;

    availableAids(): string;

    queryContext(): string;
}