// generated by diplomat-tool
import type { UserDefinedOperation } from "./UserDefinedOperation"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class OpCtx {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): OpCtx;

    addCustomOperation(opId: number, operation: UserDefinedOperation): void;

    customOpToJson(opId: number): string;

    customOpToB64(opId: number): string;
}