// generated by diplomat-tool
import { UserDefinedOperation } from "./UserDefinedOperation.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const OpCtx_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.OpCtx_destroy(ptr);
});

export class OpCtx {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("OpCtx is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            OpCtx_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.OpCtx_create();

        try {
            return new OpCtx(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    addCustomOperation(opId, operation) {
    wasm.OpCtx_add_custom_operation(this.ffiValue, opId, operation.ffiValue);

        try {}

        finally {
        }
    }

    customOpToJson(opId) {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.OpCtx_custom_op_to_json(this.ffiValue, opId, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}