// generated by diplomat-tool
import type { UserDefinedOperation } from "./UserDefinedOperation"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class OpCtx {
    get ffiValue(): pointer;


    static create(): OpCtx;

    addCustomOperation(opId: number, operation: UserDefinedOperation): void;
}