// generated by diplomat-tool
import type { ConcreteGraph } from "./ConcreteGraph"
import type { OpCtx } from "./OpCtx"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Runner {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): Runner;

    run(graph: ConcreteGraph, opCtx: OpCtx, opId: number, args: Array<number>): void;
}