// generated by diplomat-tool
import { ConcreteGraph } from "./ConcreteGraph.mjs"
import { OpCtx } from "./OpCtx.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Runner_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Runner_destroy(ptr);
});

export class Runner {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Runner is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Runner_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.Runner_create();

        try {
            return new Runner(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    run(graph, opCtx, opId, args) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const argsSlice = diplomatRuntime.DiplomatBuf.slice(wasm, args, "u32");
    wasm.Runner_run(this.ffiValue, graph.ffiValue, opCtx.ffiValue, opId, ...argsSlice.splat());

        try {}

        finally {
            functionCleanupArena.free();

        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}