// generated by diplomat-tool
import type { EdgesIter } from "./EdgesIter"
import type { NodesIter } from "./NodesIter"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ConcreteGraph {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static new_(): ConcreteGraph;

    /**
     * Returns the node key of the newly added node
     */
    addNode(value: string): number;

    deleteNode(key: number): void;

    addEdge(src: number, dst: number, weight: string): void;

    getNodes(): NodesIter;

    getEdges(): EdgesIter;
}