// generated by diplomat-tool
import { EdgesIter } from "./EdgesIter.mjs"
import { NodesIter } from "./NodesIter.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const ConcreteGraph_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.ConcreteGraph_destroy(ptr);
});

export class ConcreteGraph {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("ConcreteGraph is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            ConcreteGraph_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static new_() {

        const result = wasm.ConcreteGraph_new();

        try {
            return new ConcreteGraph(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Returns the node key of the newly added node
     */
    addNode(value) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const valueSlice = diplomatRuntime.DiplomatBuf.str8(wasm, value);

        const result = wasm.ConcreteGraph_add_node(this.ffiValue, ...valueSlice.splat());

        try {
            return result;
        }

        finally {
            functionCleanupArena.free();

        }
    }

    deleteNode(key) {
    wasm.ConcreteGraph_delete_node(this.ffiValue, key);

        try {}

        finally {
        }
    }

    addEdge(src, dst, weight) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const weightSlice = diplomatRuntime.DiplomatBuf.str8(wasm, weight);
    wasm.ConcreteGraph_add_edge(this.ffiValue, src, dst, ...weightSlice.splat());

        try {}

        finally {
            functionCleanupArena.free();

        }
    }

    getNodes() {

        const result = wasm.ConcreteGraph_get_nodes(this.ffiValue);

        try {
            return new NodesIter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    getEdges() {

        const result = wasm.ConcreteGraph_get_edges(this.ffiValue);

        try {
            return new EdgesIter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}