// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class EdgeWrapper {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    src(): number;

    dst(): number;

    weight(): string;
}