// generated by diplomat-tool
import type { EdgeWrapper } from "./EdgeWrapper"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class EdgesIter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): EdgesIter;

    next(): IteratorResult<EdgeWrapper>;
}