// generated by diplomat-tool
import type { LineColSpan } from "./LineColSpan"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class LineColSpansIter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): LineColSpansIter;

    next(): IteratorResult<LineColSpan>;
}