// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export type LineColSpan_obj = {
    lineStart: number;
    lineEnd: number;
    colStart: number;
    colEnd: number;
};



export class LineColSpan {
    get lineStart(): number;
    set lineStart(value: number);
    get lineEnd(): number;
    set lineEnd(value: number);
    get colStart(): number;
    set colStart(value: number);
    get colEnd(): number;
    set colEnd(value: number);
    /** @internal */
    static fromFields(structObj : LineColSpan_obj) : LineColSpan;

    /**
    * Create `LineColSpan` from an object that contains all of `LineColSpan`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: LineColSpan_obj);

}