// generated by diplomat-tool
import type { NewNode } from "./NewNode"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class NewNodesIter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): NewNodesIter;

    next(): IteratorResult<NewNode>;
}