// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class NodeWrapper {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    key(): number;

    value(): string;
}