// generated by diplomat-tool
import type { NodeWrapper } from "./NodeWrapper"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class NodesIter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): NodesIter;

    next(): IteratorResult<NodeWrapper>;
}