// generated by diplomat-tool
import { StringIter } from "./StringIter.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const ParseResult_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.ParseResult_destroy(ptr);
});

export class ParseResult {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("ParseResult is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            ParseResult_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    dotOfState(state) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const stateSlice = diplomatRuntime.DiplomatBuf.str8(wasm, state);
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.ParseResult_dot_of_state(this.ffiValue, ...stateSlice.splat(), write.buffer);

        try {
            return write.readString8();
        }

        finally {
            functionCleanupArena.free();

            write.free();
        }
    }

    listStates() {

        const result = wasm.ParseResult_list_states(this.ffiValue);

        try {
            return new StringIter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}