// generated by diplomat-tool
import type { StringIter } from "./StringIter"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ParseResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    dotOfState(state: string): string;

    listStates(): StringIter;
}