// generated by diplomat-tool
import type { ConcreteGraph } from "./ConcreteGraph"
import type { LineColSpansIter } from "./LineColSpansIter"
import type { NewNodesIter } from "./NewNodesIter"
import type { StringError } from "./StringError"
import type { StringIter } from "./StringIter"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class ParseResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    errorMessage(): string;

    errorSpans(): LineColSpansIter;

    dotOfState(state: string): string;

    listStates(): StringIter;

    listOperations(): StringIter;

    runOperation(g: ConcreteGraph, opName: string, args: Array<number>): NewNodesIter;
}