// generated by diplomat-tool
import { NewNodesIter } from "./NewNodesIter.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const RunOperationResult_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.RunOperationResult_destroy(ptr);
});

export class RunOperationResult {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("RunOperationResult is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            RunOperationResult_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    [Symbol.iterator]() {

        const result = wasm.RunOperationResult_to_iterable(this.ffiValue);

        try {
            return new NewNodesIter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    chainedDotTrace() {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.RunOperationResult_chained_dot_trace(this.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}