// generated by diplomat-tool
import type { NewNodesIter } from "./NewNodesIter"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class RunOperationResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    [Symbol.iterator](): NewNodesIter;

    chainedDotTrace(): string;
}