// generated by diplomat-tool
import type { StringWrapper } from "./StringWrapper"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class StringIter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    next(): IteratorResult<StringWrapper>;
}