// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class StringError {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    toString(): string;
}