// generated by diplomat-tool
import type { Program } from "./Program"
import type { StringError } from "./StringError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents the result of compiling a source file.
 *
 * The compilation may have failed, but there may still be valid intermediate states to print.
 * To check for errors and access the programs, call getProgram().
 */
export class CompileResult {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Returns the DOT representation of the intermediate state named `state`.
     */
    dotOfState(state: string): string;

    /**
     * If the compilation was successful, this returns a `Program` that can be used to run operations.
     *
     * Otherwise, this throws an error.
     */
    getProgram(): Program;
}