// generated by diplomat-tool
import type { StringError } from "./StringError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a concrete graph, i.e., the runtime state of a program.
 */
export class ConcreteGraph {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new empty concrete graph.
     */
    static create(): ConcreteGraph;

    /**
     * Returns the DOT representation of the concrete graph.
     */
    dot(): string;

    /**
     * Adds a new node to the concrete graph with the given value and returns its key.
     */
    addNode(value: string): number;

    /**
     * Adds an edge from the node with key `from` to the node with key `to` with the given value.
     */
    addEdge(from: number, to: number, value: string): void;
}