// generated by diplomat-tool
import type { CompileResult } from "./CompileResult"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Holds a bunch of top-level functions.
 */
export class Grabapl {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Call this function at the beginning of your program to initialize useful
     * Rust panic error messages.
     */
    static init(): void;

    /**
     * Parses a source file.
     */
    static parse(src: string): CompileResult;
}