// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Grabapl {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static init(): void;
}