// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * The operation context maps operation IDs (integers) to operations.
 */
export class OperationContext {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new operation context.
     */
    static create(): OperationContext;
}