// generated by diplomat-tool
import { ConcreteGraph } from "./ConcreteGraph.mjs"
import { OperationContext } from "./OperationContext.mjs"
import { StringError } from "./StringError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const Program_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.Program_destroy(ptr);
});

/**
 * Represents a program that can be executed.
 */
export class Program {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("Program is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            Program_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Returns a copy of the operation context.
     */
    opCtx() {

        const result = wasm.Program_op_ctx(this.ffiValue);

        try {
            return new OperationContext(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
        }
    }

    /**
     * Runs the operation with the given name on the provided concrete graph with the given arguments.
     */
    runOperation(g, opName, args) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const opNameSlice = diplomatRuntime.DiplomatBuf.str8(wasm, opName);
        const argsSlice = diplomatRuntime.DiplomatBuf.slice(wasm, args, "u32");
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.Program_run_operation(diplomatReceive.buffer, this.ffiValue, g.ffiValue, ...opNameSlice.splat(), ...argsSlice.splat());

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new StringError(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
                throw new globalThis.Error('StringError: ' + cause.toString(), { cause });
            }
        }

        finally {
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}