// generated by diplomat-tool
import type { ConcreteGraph } from "./ConcreteGraph"
import type { OperationContext } from "./OperationContext"
import type { StringError } from "./StringError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Represents a program that can be executed.
 */
export class Program {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Returns a copy of the operation context.
     */
    opCtx(): OperationContext;

    /**
     * Runs the operation with the given name on the provided concrete graph with the given arguments.
     */
    runOperation(g: ConcreteGraph, opName: string, args: Array<number>): void;
}