// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Catch this in a try-catch and print it with toString().
 */
export class StringError {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    toString(): string;
}