[package]
name = "simple_semantics"
version = "0.1.0"
edition = "2024"
default-run = "simple_semantics"


[dependencies]
grabapl = { path = "../../../grabapl" }

[[bin]]
name = "simple_semantics"
path = "src/main.rs"
